### ISSUE TITLE
Not reproducable

### ISSUE THREAD

**Issue by ltierney** [kevinushey/longjmp#1]
I'm not seeing the issues in the README on Linux or macOS. Can you provide a reproducible example?

The WIndows issue seems unrelated.

**Comment by ltierney** [comment]
I'm not seeing the issues in the README on Linux or macOS. Can you provide a reproducible example?

The WIndows issue seems unrelated.

**Comment by kevinushey** [comment]
Thanks for taking a look! It looks like this only reproduces when running R within RStudio. I'm not yet sure why this would make a difference.

My only guess is that perhaps RStudio is doing something behind the scenes that could be causing this. Maybe we're accidentally screwing up the protection stack, or something similar?

**Comment by ltierney** [comment]
Thanks -- I can reproduce this now. Apparently we allow
R_ReturnedValue to be NULL (i.e. a C NULL pointer). I can work around
that but want to figure out why we allow this -- there may be a good
reason but it seems like a Really Bad Idea.

Best,

luke

On Thu, 1 Feb 2018, Kevin Ushey wrote:

> 
> Thanks for taking a look! It looks like this only reproduces when running R
> within RStudio. I'm not yet sure why this would make a difference.
> 
> My only guess is that perhaps RStudio is doing something behind the scenes
> that could be causing this. Maybe we're accidentally screwing up the
> protection stack, or something similar?
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the
> thread.[ADvaVE3yQCAXezYpElDtWTGkNSP5TjwDks5tQi10gaJpZM4R2J0b.gif]
> 
> 
>

-- 
Luke Tierney
Ralph E. Wareham Professor of Mathematical Sciences
University of Iowa                  Phone:             319-335-3386
Department of Statistics and        Fax:               319-335-3017
    Actuarial Science
241 Schaeffer Hall                  email:   luke-tierney@uiowa.edu
Iowa City, IA 52242                 WWW:  http://www.stat.uiowa.edu

**Comment by ltierney** [comment]
Should be fixed in r74195. Let me know if you see any other issues.

[Remember that for this to work as intended you need the
R_ContinueUnwind() call in the catch clause.]

Best,

luke

On Fri, 2 Feb 2018, luke-tierney@uiowa.edu wrote:

> Thanks -- I can reproduce this now. Apparently we allow
> R_ReturnedValue to be NULL (i.e. a C NULL pointer). I can work around
> that but want to figure out why we allow this -- there may be a good
> reason but it seems like a Really Bad Idea.
>
> Best,
>
> luke
>
> On Thu, 1 Feb 2018, Kevin Ushey wrote:
>
>> 
>> Thanks for taking a look! It looks like this only reproduces when running R
>> within RStudio. I'm not yet sure why this would make a difference.
>> 
>> My only guess is that perhaps RStudio is doing something behind the scenes
>> that could be causing this. Maybe we're accidentally screwing up the
>> protection stack, or something similar?
>> 
>> —
>> You are receiving this because you modified the open/close state.
>> Reply to this email directly, view it on GitHub, or mute the
>> thread.[ADvaVE3yQCAXezYpElDtWTGkNSP5TjwDks5tQi10gaJpZM4R2J0b.gif]
>> 
>> 
>> 
>
>

-- 
Luke Tierney
Ralph E. Wareham Professor of Mathematical Sciences
University of Iowa                  Phone:             319-335-3386
Department of Statistics and        Fax:               319-335-3017
    Actuarial Science
241 Schaeffer Hall                  email:   luke-tierney@uiowa.edu
Iowa City, IA 52242                 WWW:  http://www.stat.uiowa.edu

**Comment by kevinushey** [comment]
Awesome news! I can confirm that all looks well with the latest version of R-devel. Thank you for taking the time to dig into this issue (and I'll fix that up in my own example).
